server:
  port:  9002

spring:
  application:
    name: service-ribbon

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    #    register-with-eureka: false
    #    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8999/eureka/
logging:
  config:  classpath:logback-spring.xml
